spring:
  application:
    name: rag-chat
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123654

  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
server:
  port: 8085
